# Copyright (c) 2017 Sony Corporation. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ubuntu:16.04

RUN apt-get update && apt-get install -y --no-install-recommends \
        bzip2 \
        ca-certificates \
        ccache \
        clang-format-3.8 \
        cmake \
        curl \
        g++ \
        git \
        libarchive-dev \
        libhdf5-dev \
        libopenmpi-dev \
        make \
        openmpi-bin \
        unzip \
        wget \
        zip \
    && cd / \
    && rm -rf /tmp/*

# Conda environment for Python versions
RUN wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
	&& bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/miniconda3 \
	&& rm -rf Miniconda3-latest-Linux-x86_64.sh

ENV PATH /opt/miniconda3/bin:$PATH
RUN set -xe \
	&& umask 0 \
	&& conda create -y -n {PYENVNAME} python={PYENVVERSION} \
	&& bash -c "source activate {PYENVNAME} \
		&& conda install \
                	pip \
                        wheel \
                        boto3 \
                        h5py \
                        mako \
                        numpy \
                        protobuf \
                        tqdm \
                        ipython \
                        pytest \
                        scipy \
                        scikit-image \
                        opencv \
		&& rm -rf /opt/miniconda3/pkgs \
		&& pip install onnx cntk \
		&& pip install Cython==0.25 autopep8 requests"

ENV PATH /opt/miniconda3/envs/{PYENVNAME}/bin:$PATH
ENV LD_LIBRARY_PATH /opt/miniconda3/envs/{PYENVNAME}/lib:$LD_LIBRARY_PATH
