# Copyright (c) 2017 Sony Corporation. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ubuntu:16.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       build-essential \
       bzip2 \
       ca-certificates \
       ccache \
       clang-format-3.8 \
       cmake \
       curl \
       g++ \
       git \
       libarchive-dev \
       libgoogle-glog-dev \
       libgtest-dev \
       libhdf5-dev \
       libiomp-dev \
       libleveldb-dev \
       liblmdb-dev \
       libopencv-dev \
       libopenmpi-dev \
       libprotobuf-dev \
       libsnappy-dev \
       libssl-dev \
       make \
       openmpi-bin \
       openmpi-doc \
       openssl \
       unzip \
       wget \
       zip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
	&& bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/miniconda3 \
	&& rm -rf Miniconda3-latest-Linux-x86_64.sh

ARG PYTHON_VERSION_MAJOR
ARG PYTHON_VERSION_MINOR
ARG PYTHON_LIB_SUFFIX
ENV PYENVNAME=py${PYTHON_VERSION_MAJOR}${PYTHON_VERSION_MINOR}
ENV PYVERNAME=${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}

ENV PATH /opt/miniconda3/bin:$PATH
RUN set -xe \
	&& umask 0 \
	&& conda create -y -n ${PYENVNAME} python=${PYVERNAME} \
	&& bash -c "source activate ${PYENVNAME} \
		&& conda install \
                	future \
                	numpy \
                	pip \
                        boto3 \
                        h5py \
                        ipython \
                        mako \
                        numpy \
                        opencv \
                        protobuf \
                        pytest \
                        scikit-image \
                        scipy \
                        tqdm \
                        wheel \
		&& rm -rf /opt/miniconda3/pkgs"

ENV PATH /opt/miniconda3/envs/${PYENVNAME}/bin:$PATH
ENV LD_LIBRARY_PATH /opt/miniconda3/envs/${PYENVNAME}/lib:$LD_LIBRARY_PATH

RUN set -xe \
	&& umask 0 \
        && cd /tmp \
        && git clone --recursive https://github.com/pytorch/pytorch.git \
        && cd pytorch \
        && git checkout 4e5dec302444143ccea4fbcc651ca55cfa5ea915 \
        && git submodule update --init \
        && mv /opt/miniconda3/envs/${PYENVNAME}/lib/libssl.so.1.0.0 \
           /opt/miniconda3/envs/${PYENVNAME}/lib/libssl.so.1.0.0.bk \
        && mv /opt/miniconda3/envs/${PYENVNAME}/lib/libcrypto.so.1.0.0 \
           /opt/miniconda3/envs/${PYENVNAME}/lib/libcrypto.so.1.0.0.bk \
        && mkdir /tmp/pytorch/build \
        && cd /tmp/pytorch/build \
        && cmake \
            -DCMAKE_PREFIX_PATH=/opt/miniconda3/envs/${PYENVNAME} \
            -DCMAKE_INSTALL_PREFIX=/opt/miniconda3/envs/${PYENVNAME} \
            -DPYTHON_EXECUTABLE=/opt/miniconda3/envs/${PYENVNAME}/bin/python \
            -DPYTHON_LIBRARY=/opt/miniconda3/envs/${PYENVNAME}/lib/libpython${PYVERNAME}${PYTHON_LIB_SUFFIX}.so \
            -DPYTHON_INCLUDE_DIR=/opt/miniconda3/envs/${PYENVNAME}/include/python${PYVERNAME}${PYTHON_LIB_SUFFIX} \
            -DBUILD_CUSTOM_PROTOBUF=ON \
            -DUSE_MPI=OFF \
            -DUSE_OPENCV=OFF \
            .. \
        && make -j4 \
        && make install \
        && mv /opt/miniconda3/envs/${PYENVNAME}/lib/libssl.so.1.0.0.bk \
           /opt/miniconda3/envs/${PYENVNAME}/lib/libssl.so.1.0.0 \
        && mv /opt/miniconda3/envs/${PYENVNAME}/lib/libcrypto.so.1.0.0.bk \
           /opt/miniconda3/envs/${PYENVNAME}/lib/libcrypto.so.1.0.0 \
        && rm -rf /tmp/*

RUN set -xe \
        && pip install pytest-runner pybind11 typing typing-extensions \
	&& umask 0 \
        && cd /tmp \
        && git clone https://github.com/onnx/onnx.git \
        && cd /tmp/onnx \
        && git checkout 3376d4438aaadfba483399fa249b841153152bc0 \
        && mv /opt/miniconda3/envs/${PYENVNAME}/lib/libssl.so.1.0.0 \
           /opt/miniconda3/envs/${PYENVNAME}/lib/libssl.so.1.0.0.bk \
        && mv /opt/miniconda3/envs/${PYENVNAME}/lib/libcrypto.so.1.0.0 \
           /opt/miniconda3/envs/${PYENVNAME}/lib/libcrypto.so.1.0.0.bk \
        && python setup.py install \
        && mv /opt/miniconda3/envs/${PYENVNAME}/lib/libssl.so.1.0.0.bk \
           /opt/miniconda3/envs/${PYENVNAME}/lib/libssl.so.1.0.0 \
        && mv /opt/miniconda3/envs/${PYENVNAME}/lib/libcrypto.so.1.0.0.bk \
           /opt/miniconda3/envs/${PYENVNAME}/lib/libcrypto.so.1.0.0 \
        && cd / \
        && rm -rf /tmp/*

RUN pip install pyyaml
RUN pip install cntk Cython==0.25 autopep8 requests

RUN cd /tmp \
    && curl -L https://www.libarchive.org/downloads/libarchive-3.3.2.tar.gz -o libarchive-3.3.2.tar.gz \
    && tar xfa libarchive-3.3.2.tar.gz \
    && mkdir libarchive-build \
    && cd libarchive-build \
    && cmake \
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
        -DENABLE_NETTLE=FALSE \
        -DENABLE_OPENSSL=FALSE \
        -DENABLE_LZO=FALSE \
        -DENABLE_LZMA=FALSE \
        -DENABLE_BZip2=FALSE \
        -DENABLE_LIBXML2=FALSE \
        -DENABLE_EXPAT=FALSE \
        -DENABLE_PCREPOSIX=FALSE \
        -DENABLE_LibGCC=FALSE \
        -DENABLE_CNG=FALSE \
        -DENABLE_TAR=FALSE \
        -DENABLE_TAR_SHARED=FALSE \
        -DENABLE_CPIO=FALSE \
        -DENABLE_CPIO_SHARED=FALSE \
        -DENABLE_CAT=FALSE \
        -DENABLE_CAT_SHARED=FALSE \
        -DENABLE_XATTR=FALSE \
        -DENABLE_ACL=FALSE \
        -DENABLE_ICONV=FALSE \
        -DENABLE_TEST=FALSE \
        ../libarchive-3.3.2 \
    && make \
    && make install \
    && cd / \
    && rm -rf /tmp/*
