# Copyright (c) 2017 Sony Corporation. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# for nnabla>=1.5.0

FROM ubuntu:18.04

ENV LC_ALL C
ENV LANG C
ENV LANGUAGE C

ARG PYTHON_VERSION_MAJOR
ARG PYTHON_VERSION_MINOR
ENV PYVERNAME=${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}

RUN apt-get update
RUN apt install -y software-properties-common
RUN add-apt-repository -y ppa:deadsnakes/ppa
RUN apt-get update

RUN apt-get install -y --no-install-recommends \
       bzip2 \
       ca-certificates \
       ccache \
       clang-format-5.0 \
       cmake \
       curl \
       g++ \
       git \
       libarchive-dev \
       libgoogle-glog-dev \
       libgtest-dev \
       libhdf5-dev \
       libleveldb-dev \
       liblmdb-dev \
       libsnappy-dev \
       libssl-dev \
       make \
       openssl \
       unzip \
       wget \
       zip \
       python3-venv \
       python${PYVERNAME} \
       python${PYVERNAME}-venv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       python${PYVERNAME}-distutils || echo "skip install python-distutils" \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py \
    && python${PYVERNAME} get-pip.py \
    && rm get-pip.py

RUN update-alternatives --install /usr/bin/python python /usr/bin/python${PYVERNAME} 0

################################################## protobuf
RUN mkdir /tmp/deps \
    && cd /tmp/deps \
    && PROTOVER=3.10.1 \
    && curl -L https://github.com/google/protobuf/archive/v${PROTOVER}.tar.gz -o protobuf-v${PROTOVER}.tar.gz \
    && tar xvf protobuf-v${PROTOVER}.tar.gz \
    && cd protobuf-${PROTOVER} \
    && mkdir build \
    && cd build \
    && cmake \
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
        -Dprotobuf_BUILD_TESTS=OFF \
        ../cmake \
    && make -j8 \
    && make install \
    && cd / \
    && rm -rf /tmp/*

################################################## requirements

ADD python/setup_requirements.txt /tmp/deps/
ADD python/requirements.txt /tmp/deps/
ADD python/test_requirements.txt /tmp/deps/

RUN pip install numpy \
    && pip install -U -r /tmp/deps/setup_requirements.txt \
    && pip install -U -r /tmp/deps/requirements.txt \
    && pip install -U -r /tmp/deps/test_requirements.txt \
    && rm -rf /tmp/*

ENV PATH /tmp/.local/bin:$PATH
ENV LD_LIBRARY_PATH /usr/local/lib64:$LD_LIBRARY_PATH
