# Copyright (c) 2017 Sony Corporation. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ubuntu:16.04

ENV LC_ALL C
ENV LANG C
ENV LANGUAGE C

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       build-essential \
       bzip2 \
       ca-certificates \
       ccache \
       clang-format-3.8 \
       cmake \
       curl \
       g++ \
       git \
       libarchive-dev \
       libgoogle-glog-dev \
       libgtest-dev \
       libhdf5-dev \
       libiomp-dev \
       libleveldb-dev \
       liblmdb-dev \
       libopencv-dev \
       libopenmpi-dev \
       libprotobuf-dev \
       libsnappy-dev \
       libssl-dev \
       make \
       openmpi-bin \
       openmpi-doc \
       openssl \
       unzip \
       wget \
       zip \
       graphviz \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN cd /tmp \
    && curl -L https://www.libarchive.org/downloads/libarchive-3.3.2.tar.gz -o libarchive-3.3.2.tar.gz \
    && tar xfa libarchive-3.3.2.tar.gz \
    && mkdir libarchive-build \
    && cd libarchive-build \
    && cmake \
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
        -DENABLE_NETTLE=FALSE \
        -DENABLE_OPENSSL=FALSE \
        -DENABLE_LZO=FALSE \
        -DENABLE_LZMA=FALSE \
        -DENABLE_BZip2=FALSE \
        -DENABLE_LIBXML2=FALSE \
        -DENABLE_EXPAT=FALSE \
        -DENABLE_PCREPOSIX=FALSE \
        -DENABLE_LibGCC=FALSE \
        -DENABLE_CNG=FALSE \
        -DENABLE_TAR=FALSE \
        -DENABLE_TAR_SHARED=FALSE \
        -DENABLE_CPIO=FALSE \
        -DENABLE_CPIO_SHARED=FALSE \
        -DENABLE_CAT=FALSE \
        -DENABLE_CAT_SHARED=FALSE \
        -DENABLE_XATTR=FALSE \
        -DENABLE_ACL=FALSE \
        -DENABLE_ICONV=FALSE \
        -DENABLE_TEST=FALSE \
        ../libarchive-3.3.2 \
    && make \
    && make install \
    && cd / \
    && rm -rf /tmp/*

ARG PYTHON_VERSION_MAJOR
ARG PYTHON_VERSION_MINOR
ENV PYVERNAME=${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}

ENV PATH /opt/miniconda3/bin:$PATH
ENV LD_LIBRARY_PATH /opt/miniconda3/lib:$LD_LIBRARY_PATH

RUN set -xe \
    && umask 0 \
    && wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/miniconda3 \
    && rm -rf Miniconda3-latest-Linux-x86_64.sh \
    && if test ${PYTHON_VERSION_MAJOR} -eq 3 -a ${PYTHON_VERSION_MINOR} -eq 5; \
       then \
            conda install -y conda=4.5.11 python=${PYVERNAME}; \
       else \
            conda install -y python=${PYVERNAME}; \
            conda update -y --all; \
       fi \
    && conda install -y \
        boto3 \
        future \
        h5py \
        ipython \
        mako \
        'numpy<1.16' \
        opencv \
        pip \
        protobuf \
        pytest \
        scikit-image \
        scipy \
        tqdm \
        wheel \
        virtualenv \
    && pip install pyyaml onnx==1.3.0 future Cython autopep8 requests \
        graphviz pytablewriter \
    && pip install cntk || true \
    && conda install -y -c pytorch pytorch-nightly-cpu \
    && rm -rf /opt/miniconda3/pkgs
