# Copyright (c) 2017 Sony Corporation. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM multiarch/debian-debootstrap:armhf-buster

ENV LC_ALL C
ENV LANG C
ENV LANGUAGE C

RUN apt-get update && apt-get install -y --no-install-recommends \
    bzip2 \
    ca-certificates \
    ccache \
    cmake \
    curl \
    g++ \
    git \
    libarchive-dev \
    libatlas-base-dev \
    libhdf5-dev \
    libopenblas-dev \
    liblapack-dev \
    make \
    pkg-config \
    python3 \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    python3-venv \
    unzip \
    wget \
    zip

ENV PROTOVER=3.10.1
RUN mkdir /tmp/deps \
    && cd /tmp/deps \
    && curl -L https://github.com/google/protobuf/archive/v${PROTOVER}.tar.gz -o protobuf-v${PROTOVER}.tar.gz \
    && tar xvf protobuf-v${PROTOVER}.tar.gz \
    && cd protobuf-${PROTOVER} \
    && mkdir build \
    && cd build \
    && cmake \
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
        -Dprotobuf_BUILD_TESTS=OFF \
        ../cmake \
    && make -j8 \
    && make install \
    && cd / \
    && rm -rf /tmp/*

############################################################ libarchive
ARG LIBARCHIVEVER=3.4.3
RUN mkdir /tmp/deps \
    && cd /tmp/deps \
    && curl -L https://github.com/libarchive/libarchive/archive/v${LIBARCHIVEVER}.tar.gz -o libarchive-${LIBARCHIVEVER}.tar.gz \
    && tar xfa libarchive-${LIBARCHIVEVER}.tar.gz \
    && mkdir libarchive-build \
    && cd libarchive-build \
    && cmake \
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DENABLE_NETTLE=FALSE -DENABLE_OPENSSL=FALSE \
        -DENABLE_LZO=FALSE -DENABLE_LZMA=FALSE -DENABLE_BZip2=FALSE \
        -DENABLE_LIBXML2=FALSE -DENABLE_EXPAT=FALSE -DENABLE_PCREPOSIX=FALSE -DENABLE_LibGCC=FALSE \
        -DENABLE_CNG=FALSE -DENABLE_TAR=FALSE -DENABLE_TAR_SHARED=FALSE -DENABLE_CPIO=FALSE \
        -DENABLE_CPIO_SHARED=FALSE -DENABLE_CAT=FALSE -DENABLE_CAT_SHARED=FALSE -DENABLE_XATTR=FALSE \
        -DENABLE_ACL=FALSE -DENABLE_ICONV=FALSE -DENABLE_TEST=FALSE \
        ../libarchive-${LIBARCHIVEVER} \
    && make -j8 \
    && make install \
    && cd / \
    && rm -rf /tmp/*

RUN python3 -m pip install --upgrade pip
RUN echo "[global]" >/etc/pip.conf
RUN echo "extra-index-url=https://www.piwheels.org/simple" >> /etc/pip.conf
RUN python3 -m pip install --no-cache-dir numpy==1.19.5
RUN python3 -m pip install --no-cache-dir scipy\<1.4
RUN python3 -m pip install --no-cache-dir \
    autopep8 \
    boto3 \
    cython \
    h5py \
    mako \
    pillow \
    protobuf \
    pytest \
    pyyaml \
    requests \
    tqdm
RUN python3 -m pip install ipython

ENV PATH /tmp/.local/bin:$PATH
