# Copyright (c) 2017 Sony Corporation. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# for nnabla>=1.5.0

FROM multiarch/ubuntu-core:armhf-xenial

ENV LC_ALL C
ENV LANG C
ENV LANGUAGE C

RUN apt-get update && apt-get install -y --no-install-recommends \
    bzip2 \
    ca-certificates \
    ccache \
    clang-format-3.8 \
    cmake \
    curl \
    g++ \
    git \
    libarchive-dev \
    libatlas-dev \
    libhdf5-dev \
    liblapack-dev \
    make \
    pkg-config \
    python3 \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    python3-venv \
    unzip \
    wget \
    zip

ENV PROTOVER=3.10.1
RUN mkdir /tmp/deps \
    && cd /tmp/deps \
    && curl -L https://github.com/google/protobuf/archive/v${PROTOVER}.tar.gz -o protobuf-v${PROTOVER}.tar.gz \
    && tar xvf protobuf-v${PROTOVER}.tar.gz \
    && cd protobuf-${PROTOVER} \
    && mkdir build \
    && cd build \
    && cmake \
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
        -Dprotobuf_BUILD_TESTS=OFF \
        ../cmake \
    && make \
    && make install \
    && cd / \
    && rm -rf /tmp/*

RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install --no-cache-dir numpy
RUN python3 -m pip install --no-cache-dir scipy\<1.4
RUN python3 -m pip install --no-cache-dir onnx\<1.6
RUN python3 -m pip install --no-cache-dir \
    autopep8 \
    boto3 \
    cython \
    h5py \
    mako \
    pillow \
    protobuf \
    pytest \
    pyyaml \
    requests \
    tqdm
RUN python3 -m pip install ipython
