#! /bin/bash
# Copyright 2017,2018,2019,2020,2021 Sony Corporation.
# Copyright 2021,2022 Sony Group Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Usage: auditwheel-nnabla <relative path to wheel>
# This will output a new wheel with manylinux_2_17 tag.

set -e

TMPDIR=$(mktemp -d)

if [ -e $1 ]
then
    INPUT=$(basename $1)
    TAG="-manylinux_2_17_"
    if [[ $INPUT == *"aarch64"* ]]; then
        TAG="-manylinux_2_31_"
    fi
    OUTPUT=$(echo $INPUT | sed "s/-linux_/$TAG/g")
    ABSDIR=$(cd $(dirname $1) && pwd)
    unzip -q -d $TMPDIR $ABSDIR/$INPUT
    cd $TMPDIR
    chmod -R u+r .
    # Replace tag linux to manylinux_x_x to fool the pip installer.
    for WHEEL in *dist-info/WHEEL
    do
        cat $WHEEL | sed "s/-linux_/$TAG/g" > $WHEEL.bak && mv $WHEEL.bak $WHEEL
    done

    CMAKE_BUILD_TYPE=$2
    # Strip shared libraries.
    if [[ "$CMAKE_BUILD_TYPE" != "Debug" ]]; then
        for STRIP_LIB in $(find . -name "*.so*")
        do
            if [[ "$STRIP_LIB" = *"cpython"* ]] || [[ "$STRIP_LIB" = *"libnnabla"* ]] ; then
                echo "Striping $STRIP_LIB"
                strip --strip-unneeded $STRIP_LIB
            fi
        done
    fi

    INCLUDE_CUDA_CUDNN_LIB_IN_WHL=$3
    if [[ "$INCLUDE_CUDA_CUDNN_LIB_IN_WHL" == "True" ]]; then
        NNABLA_EXT_SO=$(find . -name *libnnabla_cuda*.so)
        LIBDIR=$(cd $(dirname $NNABLA_EXT_SO) && pwd)
        NNABLA_EXT_SO=$(basename $NNABLA_EXT_SO)
        cd $LIBDIR
        find *.so* | while read SOFILE
        do
            if [[ "$SOFILE" = *"libcudnn_"* ]]; then
                patchelf --add-needed $SOFILE $NNABLA_EXT_SO
                patchelf --set-rpath '$ORIGIN' $NNABLA_EXT_SO
                patchelf --set-rpath '$ORIGIN' $SOFILE
                echo "Add dependency $SOFILE to $NNABLA_EXT_SO"
            fi
        done
        cd $TMPDIR
    fi

    echo "Creating $OUTPUT"
    zip -q -r $ABSDIR/$OUTPUT *
fi
rm -rf $TMPDIR
