#!/usr/bin/env python
# Copyright 2017,2018,2019,2020,2021 Sony Corporation.
# Copyright 2021 Sony Group Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import argparse
import os
import sys


tooldir = None
for _tooldir in [os.path.abspath(os.path.join(os.path.dirname(__file__)))]:
    if os.path.exists(_tooldir):
        tooldir = _tooldir
        sys.path.append(os.path.join(tooldir, 'code_formatter'))
        sys.path.append(os.path.join(tooldir, 'code_generator'))

if __name__ == '__main__':
    import auto_format_command
    parser = argparse.ArgumentParser()
    parser.add_argument('base')
    parser.add_argument('--subfolder', nargs='*',
                        default=['include', 'src', 'python', 'examples', 'tutorial'])
    parser.add_argument('--exclude', nargs='*', type=str, default=[])
    auto_format_command.command(parser.parse_args())
