#!/usr/bin/env python
import argparse
import os
import sys


tooldir = None
for _tooldir in [os.path.abspath(os.path.join(os.path.dirname(__file__)))]:
    if os.path.exists(_tooldir):
        tooldir = _tooldir
        sys.path.append(os.path.join(tooldir, 'code_formatter'))
        sys.path.append(os.path.join(tooldir, 'code_generator'))

if __name__ == '__main__':
    import auto_format_command
    parser = argparse.ArgumentParser()
    parser.add_argument('base')
    parser.add_argument('--subfolder', nargs='*',
                        default=['include', 'src', 'python', 'examples', 'tutorial'])
    parser.add_argument('--exclude', nargs='*', type=str, default=[])
    auto_format_command.command(parser.parse_args())
