FROM ubuntu:14.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    ccache \
    clang-format-3.8 \
    cmake \
    curl \
    g++ \
    make \
    python-dev \
    python-pip \
    python-setuptools \
    unzip

ENV CMAKE_PATH /opt/cmake-3.5.2
RUN curl -L https://cmake.org/files/v3.5/cmake-3.5.2.tar.gz -o cmake-3.5.2.tar.gz && \
    tar xvf cmake-3.5.2.tar.gz && \
    cd cmake-3.5.2 && mkdir build && cd build && cmake -D CMAKE_INSTALL_PREFIX=${CMAKE_PATH} .. && make && make install && \
    cd ../.. && rm -rf cmake-3.5.2
ENV PATH $CMAKE_PATH/bin:${PATH}

RUN curl -L https://github.com/google/protobuf/releases/download/v3.1.0/protoc-3.1.0-linux-x86_64.zip -o /tmp/protoc-3.1.0-linux-x86_64.zip \
    && cd /usr/local \
    && unzip /tmp/protoc-3.1.0-linux-x86_64.zip \
    && chmod 755 /usr/local/bin/protoc \
    && rm -f /tmp/protoc-3.1.0-linux-x86_64.zip readme.txt

ADD python/setup_requirements.txt /tmp/deps/
RUN pip install -U -r /tmp/deps/setup_requirements.txt
ADD python/requirements.txt /tmp/deps/
RUN pip install -U -r /tmp/deps/requirements.txt
ADD python/test_requirements.txt /tmp/deps/
RUN pip install -U -r /tmp/deps/test_requirements.txt

# Optioinal
RUN pip install -U ipython
