# Copyright (c) 2017 Sony Corporation. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


csrc_defines = """// Copyright (c) 2017 Sony Corporation. All Rights Reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// *WARNING*
// THIS FILE IS AUTO-GENERATED BY CODE GENERATOR.
// PLEASE DO NOT EDIT THIS FILE BY HAND!

#ifndef H_{name_upper}_INFERENCE_H__
#define H_{name_upper}_INFERENCE_H__

#ifdef __cplusplus
extern "C" {{
#endif /* __cplusplus */

void* {prefix}_allocate_context(void);
int {prefix}_init_context(void* context);
int {prefix}_free_context(void* context);

int {prefix}_num_of_input(void* context);
float* {prefix}_input_buffer(void* context, int index);
int {prefix}_num_of_output(void* context);
float* {prefix}_output_buffer(void* context, int index);

int {prefix}_inference(void* context);

#ifdef __cplusplus
}}
#endif /* __cplusplus */

#endif //H_{name_upper}_INFERENCE_H__
"""


csrc_implements = """// Copyright (c) 2017 Sony Corporation. All Rights Reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// *WARNING*
// THIS FILE IS AUTO-GENERATED BY CODE GENERATOR.
// PLEASE DO NOT EDIT THIS FILE BY HAND!

#include "{name}_inference.h"

#include <nnablart/functions.h>

void* {prefix}_allocate_context(void)
{{
  WHOAMI("\\n");
}}

int {prefix}_init_context(void* context)
{{
  WHOAMI("\\n");
}}

int {prefix}_free_context(void* context)
{{
  WHOAMI("\\n");
}}

int {prefix}_num_of_input(void* context)
{{
  WHOAMI("\\n");
}}

float* {prefix}_input_buffer(void* context, int index)
{{
  WHOAMI("\\n");
}}

int {prefix}_num_of_output(void* context)
{{
  WHOAMI("\\n");
}}

float* {prefix}_output_buffer(void* context, int index)
{{
  WHOAMI("\\n");
}}

int {prefix}_inference(void* context)
{{
  WHOAMI("\\n");
}}
"""

csrc_example = """// Copyright (c) 2017 Sony Corporation. All Rights Reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// *WARNING*
// THIS FILE IS AUTO-GENERATED BY CODE GENERATOR.
// PLEASE DO NOT EDIT THIS FILE BY HAND!

#include <stdio.h>
#include "{name}_inference.h"

int main(int argc, char* argv[])
{{
  int i;
  for(i = 0; i < argc; i++ ) {{
    printf("  %d: %s\\n", i, argv[i]);
  }}
  void* context = {prefix}_allocate_context();
  {prefix}_free_context(context);
}}
"""


csrc_gnumake = """# Copyright (c) 2017 Sony Corporation. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# *WARNING*
# THIS FILE IS AUTO-GENERATED BY CODE GENERATOR.
# PLEASE DO NOT EDIT THIS FILE BY HAND!

all: {name}_example

{name}_example: {name}_example.c {name}_inference.c

"""
