# Copyright (c) 2017 Sony Corporation. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# *WARNING*
# THIS FILE IS AUTO-GENERATED BY CODE GENERATOR.
# PLEASE DO NOT EDIT THIS FILE BY HAND!
# If you want to modify this file, edit following files.
# - build-tools/code_generator/generator/generate_python_src_nnabla_utils_save_function_py.py
# - build-tools/code_generator/templates/python_src_nnabla_utils_save_function_py_template.py
'''
.. note::
    This module is auto-generated from

    - :file:`build-tools/code_generator/generator/generate_python_src_nnabla_utils_save_function_py.py`
    - :file:`build-tools/code_generator/templates/python_src_nnabla_utils_save_function_py_template.py`
'''


def _create_function_nntxt(f, name, function):
    f.name = name
    f.type = function['type']
    f.input.extend(function['inputs'])
    f.output.extend(function['outputs'])
{create_function_args}
