// Copyright (c) 2017 Sony Corporation. All Rights Reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// *WARNING*
// THIS FILE IS AUTO-GENERATED BY CODE GENERATOR.
// PLEASE DO NOT EDIT THIS FILE BY HAND!
// If you want to modify this file, edit following files.
// - build-tools/code_generator/templates/src_nbla_utils_nnp_impl_create_function_cpp_template.cpp
// - build-tools/code_generator/generator/generate_src_nbla_utils_nnp_impl_create_function_cpp.py


#include "nnp_impl.hpp"

#include <nbla/logger.hpp>
#include <fstream>

#include <nbla/computation_graph/computation_graph.hpp>
#include <nbla/variable.hpp>
#include <nbla/function.hpp>
{function_includes}


namespace nbla {{ namespace utils {{ namespace nnp {{
  shared_ptr<nbla::CgFunction> NetworkImpl::create_cgfunction(const ::Function& func) {{
    {function_creator}
    return nullptr;
  }}
}}}}}}
